<a href="https://colab.research.google.com/github/jingyue-nancy-gao/ML-Data2/blob/main/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Problems

____________

#### Import NumPy as np

In [1]:
import numpy as np

# The import numpy portion of the code tells Python to bring the NumPy library into your current environment.

#### Create an array of 20 zeros 

In [3]:
np.zeros(20)

# numpy.zeros(shape, dtype=float, order='C', *, like=None)
# Return a new array of given shape and type, filled with zeros.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Create an array of 10 ones

In [12]:
np.ones(10)

# numpy.ones(shape, dtype=None, order='C', *, like=None)
# Return a new array of given shape and type, filled with ones.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [8]:
np.arange(10, 51)

# numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
# Return evenly spaced values within a given interval.

# arange(start, stop): Values are generated within the half-open interval [start, stop).

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [9]:
np.arange(10, 51, 2)

# numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
# Return evenly spaced values within a given interval.

# arange(start, stop, step) Values are generated within the half-open interval [start, stop), with spacing between values given by step.

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
arr = np.arange(9)

In [11]:
arr.reshape(3,3)

# numpy.reshape(a, newshape, order='C')
# Gives a new shape to an array without changing its data.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [13]:
np.eye(3)

# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
# Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [18]:
np.random.rand(1)

# rand(d0, d1, ..., dn)
# Random values in a given shape.

array([0.40138537])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [19]:
np.random.randn(25)

# randn(d0, d1, ..., dn)
# Return a sample (or samples) from the "standard normal" distribution.

array([ 1.74420035,  1.54612841,  0.39539877,  0.6544444 ,  0.79773741,
       -0.95609804,  0.51575217, -1.45202413,  0.19555718, -0.79092029,
        1.11174693, -0.75865123,  0.58400555,  1.36511419, -2.02125043,
        0.63374115, -0.67719458,  0.57381234, -0.67807194, -1.19762298,
        0.69255729,  1.8271223 , -0.0747652 ,  1.01452437,  0.71527793])

#### Create the following matrix:

In [37]:
arr = (np.arange(100)+1)/100

In [38]:
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [20]:
np.linspace(0, 1, 20)

# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

# Return evenly spaced numbers over a specified interval.
# Returns num evenly spaced samples, calculated over the interval [start, stop].
# The endpoint of the interval can optionally be excluded.

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [27]:
# https://numpy.org/doc/stable/user/basics.indexing.html?highlight=indexing%20selection

In [21]:
import numpy as np
#mat = np.arange(1,27).reshape(5,5)
mat = np.arange(1,28).reshape(9,3)
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat = np.arange(1,26).reshape(5,5)
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [23]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [97]:
mat[3][4]

20

20

In [24]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [25]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

mat[4,0:]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [26]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

mat[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now,

#### Get the sum of all the values in mat

In [28]:
mat.sum()

# numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
# Sum of array elements over a given axis.

325

325

#### Get the standard deviation of the values in mat

In [29]:
np.std(mat)

# numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
# Compute the standard deviation along the specified axis.

7.211102550927978

7.2111025509279782

#### Get the sum of all the columns in mat

In [31]:
sum_of_colunms = np.sum(mat, axis = 0)
sum_of_colunms

# numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
# Compute the standard deviation along the specified axis.

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

# Cheers!